apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub8ts-hello-app
  namespace: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kub8ts-hello-app
  template:
    metadata:
      labels:
        app: kub8ts-hello-app
    spec:
      containers:
        - name: kub8ts-hello-app
          image: europe-west4-docker.pkg.dev/quiet-radius-481507-f6/kub8ts-app-repo/kub8ts-hello-app:latest
          ports:
            - containerPort: 3000
