apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kub8ts-hello-app
  namespace: my-application
spec:
  ingressClassName: nginx
  rules:
    - host: my-application.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kub8ts-hello-app
                port:
                  number: 80
