apiVersion: v1
kind: Service
metadata:
  name: kub8ts-hello-app
  namespace: my-application
spec:
  selector:
    app: kub8ts-hello-app
  ports:
    - protocol: TCP
      port: 80        # зовнішній порт сервісу
      targetPort: 3000 # порт контейнера
  type: ClusterIP
